### ISSUE TITLE
Using MultiDataset and ResizedDataset simultaneously gives rise to an AttributeError

### ISSUE THREAD

**Issue by sangho-vision** [tmbdev/webdataset#9]
Hello,
when I used `ResizedDataset` and `MultiDataset`, I encountered the following error:
```python
# Used code
import webdataset as wds
dataset = wds.Dataset(url).shuffle(100).decode()
dataset = wds.ResizedDataset(dataset, 5)
loader = wds.MultiDataset(dataset, workers=2, nominal=5, pin_memory=False).shuffle(2).batched(2)
for sample in loader:
   ...
```

```
Process Process-1:
Traceback (most recent call last):
...
  File ".../webdataset/multi.py", line 64, in _parallel_job
    D("job", i, "done", dataset.sample_urls)
AttributeError: 'ResizedDataset' object has no attribute 'sample_urls'
Process Process-2:
Traceback (most recent call last):
...
  File ".../webdataset/multi.py", line 64, in _parallel_job
    D("job", i, "done", dataset.sample_urls)
AttributeError: 'ResizedDataset' object has no attribute 'sample_urls'
```

Please check out this issue.
Thank you.

**Comment by tmbdev** [comment]
ResizedDataset was primarily intended as a workaround for limitations of DataLoader with IterableDatasets, so you may not need it with MultiDataset.

However, this still looks like a bug and I'll look into fixing it.

**Comment by tmbdev** [comment]
It's fixed. You can use ResizedDataset with MultiDataset now.
